export function getStores() {
    return [
        {
            name: 'Fjordbuda Geiranger',
            mail: '',
            tlf: '',
            adress: 'Rasmus Rønnebergs gate 12',
            zip: '6216 Geiranger',
        },
        {
            name: 'Fjordbuda Ålesund',
            mail: '',
            tlf: '',
            adress: 'Kongens Gate 8',
            zip: '6002 Ålesund',
        },
        {
            name: 'Geiranger Gatekjøkken',
            mail: '',
            tlf: '',
            adress: 'Ørnevegen 6',
            zip: '6216 Geiranger',
        },
        {
            name: 'Geiranger Sweater Shop',
            mail: '',
            tlf: '',
            adress: 'Gågata',
            zip: '6216 Geiranger',
        },
        {
            name: 'Vinjenaustet Geiranger',
            mail: '',
            tlf: '',
            adress: 'Gågata',
            zip: '6216 Geiranger',
        },
        {
            name: 'Parken Souvenir Ålesund',
            mail: '',
            tlf: '',
            adress: 'Storgata 15',
            zip: '6002 Ålesund',
        },
        {
            name: 'House of Norway Ålesund',
            mail: '',
            tlf: '',
            adress: 'Notenesgata 14',
            zip: '6002 Ålesund',
        },
        {
            name: 'Ålesund Sweater Shop',
            mail: '',
            tlf: '',
            adress: 'Notenesgata 14',
            zip: '6002 Ålesund',
        },
        {
            name: 'Ålesund Tourist Shop',
            mail: '',
            tlf: '',
            adress: 'Kongens Gate 13',
            zip: '6002 Ålesund',
        },
        {
            name: 'Fjordbuda Molde',
            mail: '',
            tlf: '',
            adress: 'Storgt 10-12-14',
            zip: '6413 Molde',
        },
        {
            name: 'Fjordbuda Stryn',
            mail: '',
            tlf: '',
            adress: 'Tonningsgata 14',
            zip: '6783 Stryn',
        },
        {
            name: 'Fjordbuda Olden',
            mail: '',
            tlf: '',
            adress: '',
            zip: '6788 Olden',
        },
        {
            name: 'Olden Outlet',
            mail: '',
            tlf: '',
            adress: '',
            zip: '6788 Olden',
        },
        {
            name: 'Olden Souvenir',
            mail: '',
            tlf: '',
            adress: '',
            zip: '6788 Olden',
        },
        {
            name: 'Fjordbuda Hellesylt',
            mail: '',
            tlf: '',
            adress: 'Hellesyltvegen 42',
            zip: '6218 Hellesylt',
        },
        {
            name: 'Fjordbuda Nordfjordeid',
            mail: '',
            tlf: '',
            adress: 'Kaiveien 12',
            zip: '6770 Nordfjordeid',
        },
        {
            name: 'Fjordbuda Åndalsnes',
            mail: '',
            tlf: '',
            adress: 'Vollan 1',
            zip: '6300 Åndalsnes',
        },
        {
            name: 'Fjellbuda Lom',
            mail: '',
            tlf: '',
            adress: 'Bergomsvegen 48',
            zip: '2686 Lom',
        },
        {
            name: 'Fjordbuda Trondheim',
            mail: '',
            tlf: '',
            adress: 'Sjøgangen 6, Trappehuset',
            zip: '7011 Trondheim',
        },
        {
            name: 'House of Norway 1 Trondheim',
            mail: '',
            tlf: '',
            adress: 'Olav Tryggvasons gate 16',
            zip: '7011 Trondheim',
        },
        {
            name: 'House of Norway 2 Trondheim',
            mail: '',
            tlf: '',
            adress: 'Olav Tryggvasons gate 24',
            zip: '7011 Trondheim',
        },
        {
            name: 'Fjordbuda Skagen',
            mail: '',
            tlf: '',
            adress: 'Øvre Holmengate 1',
            zip: '4006 Stavanger',
        },
        {
            name: 'Fjordbuda Stavanger',
            mail: '',
            tlf: '123123',
            adress: 'Kirkegata 30',
            zip: '4006 Stavanger',
        },
        {
            name: 'Sentrum Souvenir',
            mail: '',
            tlf: '',
            adress: 'Skagen 9',
            zip: '4006 Stavanger',
        },
        {
            name: 'Stavanger Souvenir Shop',
            mail: '',
            tlf: '',
            adress: 'Strandkaien 28',
            zip: '4005 Stavanger',
        },
        {
            name: 'Strandbuda Souvenir',
            mail: '',
            tlf: '',
            adress: 'Strandkaien 42',
            zip: '4005 Stavanger',
        },
        {
            name: 'Fjordbuda Haugesund',
            mail: '',
            tlf: '',
            adress: 'Haralds gt 114',
            zip: '5527 Haugesund',
        },
    ];
}
